# Generated by Django 5.0.7 on 2024-07-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultsUI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resumeParser',
            new_name='interviewTest',
        ),
    ]
